AprendeAyudando/AprendeAyudando/urls.py
from django.contrib import admin
from django.urls import include, path

from django.contrib.auth import views as auth_views
from django.conf.urls import url

from django.conf import settings
from django.conf.urls.static import static

from . import views

from django.views.generic import TemplateView

urlpatterns = [
    path('', views.landingpage),

    url(r'^schedule/', include('schedule.urls')),
    url(r'^fullcalendar/', TemplateView.as_view(template_name="calendar/fullcalendar.html"), name='fullcalendar'),

    url('register/', views.user_register, name='user_register'),
    url('account/', views.account, name='account'),
    url('accountdelete/', views.delete_account, name='account_delete'),
    
    path('accounts/', include('django.contrib.auth.urls')),
        # accounts/login/ [name='login']
        # accounts/logout/ [name='logout']
        # accounts/password_change/ [name='password_change']
        # accounts/password_change/done/ [name='password_change_done']
        # accounts/password_reset/ [name='password_reset']
        # accounts/password_reset/done/ [name='password_reset_done']
        # accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
        # accounts/reset/done/ [name='password_reset_complete']
    
    path('admin/', admin.site.urls),
    path('forum/', include('forum.urls')),
    path('courses/', include('courses.urls')),
    path('activity/', include('activity.urls')),
    path('news/', include('news.urls')),
    path('requestpermissions/', include('request_permissions.urls')),
    path('quiz/', include('quiz.urls')),
    path('review/', include('review.urls')),
    path('resources/', include('resources.urls')),
    path('recoverpassword/', views.recoverpassword, name="recoverpassword"),
    path('modify/<str:username>', views.modify, name="modify"),
    path('update/<str:username>', views.update, name="update"),
    path('messaging/', include('messaging.urls')),
]

admin.site.site_header = 'Administración Aprende Ayudando'
admin.site.index_title = 'Administración'
admin.site.site_title = 'Aprende Ayudando'


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AprendeAyudando/news/urls.py
from django.urls import path
from . import views
from news.views import (NewsList, NewsCreate, NewsDetail, NewsUpdate, NewsDelete)


app_name = 'news'
urlpatterns = [
    path('', NewsList.as_view(), name='news-list'),
    path('news/add/', NewsCreate.as_view(), name='news-add'),
    path('news/<int:pk>/update/', NewsUpdate.as_view(), name='news-update'),
    path('news/<int:pk>/delete/', NewsDelete.as_view(), name='news-delete'),
    path('news/<int:pk>/', NewsDetail.as_view(), name='news-detail'),
]

AprendeAyudando/request_permissions/urls.py
from django.urls import path
from . import views

app_name = 'request_permissions'
urlpatterns = [
    path('', views.index, name='index'), #/requestpermissions
    path('create/<str:requestType>', views.createRequest, name='create'),
    path('give/', views.give_permissions, name='give_permissions'),
    path('accept/<int:request_id>/', views.accept, name='accept'),
    path('deny/<int:request_id>/', views.deny, name='deny'),
    path('redirectForm/<str:requestType>', views.redirectForm, name='redirectForm'),
]

AprendeAyudando/request_permissions/models.py
from django.db import models
from django.contrib.auth import get_user_model

ESTUDIANTE = 'Estudiante'
ADMINISTRADOR = 'Administrador'
ENTIDADPUBLICOPRIVADA = 'EntidadPublicoPrivada'
PROFESOR = 'Profesor'

ROLES =  (
    (ESTUDIANTE, ESTUDIANTE),
    (ADMINISTRADOR, ADMINISTRADOR),
    (ENTIDADPUBLICOPRIVADA, ENTIDADPUBLICOPRIVADA),
    (PROFESOR,PROFESOR),
)

class Request_permissions(models.Model):
    pub_date = models.DateTimeField(verbose_name="Fecha de Petición", auto_now_add=True)
    requester = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    role = models.CharField(max_length=25, choices=ROLES, default='Estudiante')
    requester_name = models.CharField(max_length=30, null=True, blank=True)
    requester_email = models.EmailField(max_length=40, null=True, blank=True)
    phone = models.CharField(max_length=12, null=True, blank=True)
    organization_name = models.CharField(max_length=30, null=True, blank=True)

    def __str__(self):
        return self.requester_name
    
    class Meta:
        # Como se muestra en la web de admin
        verbose_name = "Solicitud de permisos"
        verbose_name_plural = "Solicitudes de permisos"

AprendeAyudando/AprendeAyudando/forms.py
from django import forms
from django.contrib.auth.models import User
from django.db import models
from django.forms import ModelForm

class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password_repeat = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))

class RecoverForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))

class UploadForm(forms.ModelForm):
    username = forms.CharField(disabled=True, widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}), required=False)
    password_repeat = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}), required=False)
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'password_repeat', 'first_name', 'last_name']

AprendeAyudando/AprendeAyudando/views.py
from django.shortcuts import render
from django.contrib.auth.models import User, Group
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.contrib.auth import login, logout
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.core.mail import send_mail, EmailMultiAlternatives
from django.conf import settings
from .forms import RegisterForm, RecoverForm, UploadForm
import random
import string

def has_group(user, group_name):
    group = Group.objects.get(name=group_name)
    return True if group in user.groups.all() else False

def landingpage(request):
    grupo = 'Invitado'
    if request.user.has_perm('courses.view_course'):
        grupo = 'Estudiante'
    if request.user.has_perm('courses.add_course'):
        grupo = 'Profesor'
    if request.user.has_perm('activity.add_activity'):
        grupo = 'Entidad'

    context = {
        'grupo': grupo
    }
    return render(request, 'landingpage/index.html', context)

def news(request):
    return render(request, 'news/index.html')

@login_required
def account(request):
    return render(request, 'landingpage/account.html')

@login_required
def delete_account(request):
    if request.method == 'POST':
        if "cancel" in request.POST:
            return redirect('/account')
        else:
            request.user.delete()
            return redirect('/')

    return render(request, 'landingpage/delete_account.html')
    
def user_register(request):
    # if this is a POST request we need to process the form data
    template = 'registration/register.html'
   
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RegisterForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            if User.objects.filter(username=form.cleaned_data['username']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'El nombre de usuario ya existe.'
                })
            elif User.objects.filter(email=form.cleaned_data['email']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'El correo electrónico ya existe.'
                })
            elif form.cleaned_data['password'] != form.cleaned_data['password_repeat']:
                return render(request, template, {
                    'form': form,
                    'error_message': 'Las contraseñas no coinciden.'
                })
            else:
                # Create the user:
                user = User.objects.create_user(
                    form.cleaned_data['username'],
                    form.cleaned_data['email'],
                    form.cleaned_data['password']
                )
                user.first_name = form.cleaned_data['first_name']
                user.last_name = form.cleaned_data['last_name']
                user.save()
               
                # add role 'student' to new user
                studentGroup = Group.objects.get(name='Estudiante')
                studentGroup.user_set.add(user)

                # log the user in
                login(request, user)
               
                # redirect to accounts page
                return HttpResponseRedirect(reverse('account'))

   # No post data availabe, let's just show the page.
    else:
        form = RegisterForm()

    return render(request, template, {'form': form})

def recoverpassword(request):
    # if this is a POST request we need to process the form data
    template = 'registration/recoverpassword.html'
   
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        miForm = RecoverForm(request.POST)
        # check whether it's valid:
        if miForm.is_valid():
            if User.objects.filter(email=miForm.cleaned_data['email']).exists():
                # Minuto 19:19
                infForm=miForm.cleaned_data

                size = 12
                chars = string.ascii_uppercase+string.ascii_lowercase+string.digits

                newPass = ''.join(random.choice(chars) for x in range(size))
                
                user = User.objects.get(email=infForm['email'])
                user.set_password(newPass)
                user.save()

                subject = 'Solicitud de nueva contraseña'
                email_from = settings.EMAIL_HOST_USER 
                email_to = [infForm['email']]
                text_content = "ERROR"
                html_content = """  <table style="max-width: 600px; text-align: center; padding: 10px; margin:0 auto; border-collapse: collapse;">
                                        <tr>
                                            <td style="background-color: #ecf0f1; text-align: center; padding: 0">
                                                <a href="http://127.0.0.1:8000/">
                                                    <img width="20%" style="display:block; margin: 1.5% 3%; text-align: center;" src="https://aprendeayudando.herokuapp.com/static/general/images/logoTransparent.png">
                                                </a>
                                            </td>
                                        </tr>
                                        
                                        <tr>
                                            <td style="background-color: #ecf0f1">
                                                <div style="color: #34495e; margin: 4% 10% 2%; text-align: center;font-family: sans-serif">
                                                    <h2 style="color: #ff7d97; margin: 0 0 7px">¿Ha olvidado su contraseña?</h2>
                                                    <p style="margin: 2px; font-size: 15px">""" +  "Buenas, %s %s</p>" %(user.first_name, user.last_name) + """<p style="margin: 2px; font-size: 15px">
                                                        Ha solicitado una nueva contraseña en la plataforma AprendeAyudando, su nueva contraseña es: <strong>""" + "%s" %newPass + """</strong></p>
                                                    <br>
                                                    <div style="width: 100%; text-align: center">
                                                        <a style="text-decoration: none; border-radius: 5px; padding: 11px 23px; color: white; background-color: #3498db" href="http://127.0.0.1:8000/accounts/login/">Iniciar Sesión</a>	
                                                    </div>
                                                    <p style="color: #b3b3b3; font-size: 12px; text-align: center;margin: 30px 0 0">AprendeAyudando 2021</p>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>"""

                msg = EmailMultiAlternatives(subject, text_content, email_from, email_to)
                msg.attach_alternative(html_content, "text/html")
                msg.send()
                
                return render(request, template, {
                    'form': miForm,
                    'message': 'La nueva contraseña ha sido enviada a su correo electrónico.'
                })
            else:
                return render(request, template, {
                    'form': miForm,
                    'error_message': 'Inténtelo de nuevo. El correo electrónico no existe.'
                })
            

   # No post data availabe, let's just show the page.
    else:
        miForm = RecoverForm()

    return render(request, template, {'form': miForm})

@login_required
def modify(request, username):
    template = 'registration/modify.html'
    user = User.objects.get(username=username)
    if not request.user == user:
        return HttpResponseForbidden()
    modForm = UploadForm(instance=user)
    return render(request, template, {'form': modForm, 'username':username})

@login_required
def update(request, username):
    template = 'registration/modify.html'
    user = User.objects.get(username=username)
    userEmail = user.email
    modForm = UploadForm(request.POST, instance=user)
    if request.method == 'POST':
        if modForm.is_valid():

            infForm=modForm.cleaned_data
            email = infForm['email']
            password = infForm['password']
            confpassword = infForm['password_repeat']
            firstName = infForm['first_name']
            lastName = infForm['last_name']

            if User.objects.filter(email=email).exists() and userEmail != email:
                    return render(request, template, {
                        'form': modForm,
                        'error_message': 'El correo electrónico ya existe.'
                    })
            elif password != confpassword:
                    return render(request, template, {
                        'form': modForm,
                        'error_message': 'Las contraseñas no coinciden.'
                    })
            else:
                
                user.email = email
                user.first_name = firstName
                user.last_name = lastName
                
                if password != "":
                    user.set_password(password)
                    user.save()

                    subject = 'Cambio de contraseña'
                    email_from = settings.EMAIL_HOST_USER 
                    email_to = [infForm['email']]
                    text_content = "ERROR"
                    html_content = """  <table style="max-width: 600px; text-align: center; padding: 10px; margin:0 auto; border-collapse: collapse;">
                                            <tr>

AprendeAyudando/AprendeAyudando/templates/request_permissions/give_permissions.html
{% extends "registration/base.html" %}
{% block title %}AprendeAyudando - Proporcionar permisos{% endblock %}

{% block style %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'activity/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'profile/style.css' %}">
{% endblock %}

{% block content %}

<section class="bg-white text-dark py-5 min-vh-100">

    <div class="container py-5">
        <h2>Proporcionar permisos</h2>
        <h3>Solicitudes</h3>
        {% if permission_requests %}
            <table class="table text-center">
            <thead>
                <tr>
                    <th><strong style="font-size:20px">Nombre usuario</strong></th>
                    <th><strong style="font-size:20px">Rol deseado</strong></th>
                    <th><strong style="font-size:20px">Acción</strong></th>
                </tr>
            </thead>
            <tbody>
            {% for selected_request in permission_requests %}
                <tr>
                    <td><strong>{{ selected_request.requester.username }}</strong></td>
                    <td><strong>{{ selected_request.role }}</strong></td>
                    <td>
                        <ul class="actions">
                            <li style="margin-left: 20%;">
                                <a href="{% url 'request_permissions:deny' selected_request.id %}" class="button special" type="submit" name="deny">Denegar</a>
                            </li>
                            <li style="margin-left: 20%;">
                                <a href="{% url 'request_permissions:accept' selected_request.id %}" type="submit" name="accept">Aceptar</a>
                            </li>
                        </ul>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        {% else %}
            <p>No hay solicitudes de permisos disponibles.</p>
        {% endif %}
    </div>

</section>



{% endblock %}

AprendeAyudando/AprendeAyudando/templates/request_permissions/no_permission.html
{% extends "registration/base.html" %}
{% block title %}AprendeAyudando - Proporcionar permisos{% endblock %}

{% block content %}

<section class="bg-white text-dark py-5 min-vh-100">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'profile/style.css' %}">

    <div class="container py-5 text-center%">
        <h2>No tienes permisos suficientes para ver esta página</h2>
        <h3>Se requiere de rol de Administrador o permisos para aceptar peticiones.</h3>
    </div>

</section>



{% endblock %}

AprendeAyudando/AprendeAyudando/templates/request_permissions/request_form.html
{% extends "registration/base.html" %}
{% block title %}AprendeAyudando - Solicitar permisos{% endblock %}

{% block content %}

<section class="bg-white text-dark py-5 min-vh-100">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'profile/style.css' %}">
    <div class="container py-5 text-center">
        {% if solicitudExistente %}
                <h2>Ya ha enviado una solicitud.</h4>
                <a href="/account" class="btn btn-warning btn-lg">Volver a mi perfil</a>
            </div>
        {% else %}
                <h2>Solicitar permisos</h2>
                <a  href="{% url 'request_permissions:redirectForm' 'Profesor' %}" class="btn btn-warning btn-lg">Profesor</a>
                <a  href="{% url 'request_permissions:redirectForm' 'EntidadPublicoPrivada' %}" class="btn btn-warning btn-lg">Entidad Público/Privada</a>
            </div>
        {% endif %}
    </div>
    
</section>



{% endblock %}

AprendeAyudando/AprendeAyudando/templates/request_permissions/request_form_ent.html
{% extends "registration/base.html" %}
{% block title %}AprendeAyudando - Solicitar permisos Entidad Público/Privada{% endblock %}

{% block content %}

<section class="bg-white text-dark py-5 min-vh-100">
    <div class="container py-5 text-center">
        <h2>Solicitar permisos de Entidad Público/Privada</h2>
        <form action="{% url 'request_permissions:create' 'EntidadPublicoPrivada' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="org">Nombre de la organización:</label>
                <input type="text" name="org" class="form-control text-center" id="">
            </div>
            <div class="form-group">
                <label for="telefono">Número de teléfono:</label>
                <input type="text" name="telefono" class="form-control text-center" id="">
            </div>
            <input type="submit" value="Enviar solicitud" class="btn btn-secondary btn-lg">
        </form>
    </div>
</section>



{% endblock %}

AprendeAyudando/AprendeAyudando/templates/request_permissions/request_form_prof.html
{% extends "registration/base.html" %}
{% block title %}AprendeAyudando - Solicitar permisos profesor{% endblock %}

{% block content %}

<section class="bg-white text-dark py-5 min-vh-100">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'profile/style.css' %}">

    <div class="container py-5 text-center">
        <h2>Solicitar permisos de profesor</h2>
        <form action="{% url 'request_permissions:create' 'Profesor' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="telefono">Número de teléfono:</label>
                <input type="text" name="telefono" class="form-control text-center" id="">
            </div>
            <input type="submit" value="Enviar solicitud" class="btn btn-secondary btn-lg">
        </form>
    </div>
    
</section>



{% endblock %}