AprendeAyudando/AprendeAyudando/urls.py
from django.contrib import admin
from django.urls import include, path

from django.contrib.auth import views as auth_views
from django.conf.urls import url

from django.conf import settings
from django.conf.urls.static import static

from . import views

from django.views.generic import TemplateView

urlpatterns = [
    path('', views.landingpage),

    url(r'^schedule/', include('schedule.urls')),
    url(r'^fullcalendar/', TemplateView.as_view(template_name="calendar/fullcalendar.html"), name='fullcalendar'),

    url('register/', views.user_register, name='user_register'),
    url('account/', views.account, name='account'),
    url('accountdelete/', views.delete_account, name='account_delete'),
    
    path('accounts/', include('django.contrib.auth.urls')),
        # accounts/login/ [name='login']
        # accounts/logout/ [name='logout']
        # accounts/password_change/ [name='password_change']
        # accounts/password_change/done/ [name='password_change_done']
        # accounts/password_reset/ [name='password_reset']
        # accounts/password_reset/done/ [name='password_reset_done']
        # accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
        # accounts/reset/done/ [name='password_reset_complete']
    
    path('admin/', admin.site.urls),
    path('forum/', include('forum.urls')),
    path('courses/', include('courses.urls')),
    path('activity/', include('activity.urls')),
    path('news/', include('news.urls')),
    path('requestpermissions/', include('request_permissions.urls')),
    path('quiz/', include('quiz.urls')),
    path('review/', include('review.urls')),
    path('resources/', include('resources.urls')),
    path('recoverpassword/', views.recoverpassword, name="recoverpassword"),
    path('modify/<str:username>', views.modify, name="modify"),
    path('update/<str:username>', views.update, name="update"),
    path('messaging/', include('messaging.urls')),
]

admin.site.site_header = 'Administración Aprende Ayudando'
admin.site.index_title = 'Administración'
admin.site.site_title = 'Aprende Ayudando'


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AprendeAyudando/activity/urls.py
from django.urls import path
from . import views

app_name = 'activity'
urlpatterns = [
    path('', views.index, name='index'), # /activity/
    path('inscription/<int:activity_id>/', views.inscription, name='inscription'), # /activity/inscription/1/
    path('<int:activity_id>/', views.join, name='join'), # /activity/1/
    path('leave/<int:activity_id>/', views.leave, name='leave'), # /activity/leave/1/
    path('create/', views.createActivity, name='create'), #/activity/create/
     path('update/<int:activity_id>/', views.update, name='update'), # /activity/update/1/
    path('delete/<int:activity_id>/', views.delete, name='delete'), # /activity/delete/1/,
    path('enrolled/', views.enrolled, name='enrolled'),# /activity/enrolled/
    path('<int:activity_id>/activityrequest/', views.view_activity_request, name='activityrequest'), # /activity/1/activityrequest/
    path('<int:activity_id>/action_activity_request/', views.action_activity_request, name='action_activity_request'), # /activity/1/action_activityrequest/
    path('users/<int:activity_id>/', views.users, name='users'), # /activity/users/1/
    path('removeUser/<int:activity_id>/<int:user_id>/', views.removeUser, name='removeUser'), # /activity/removeUser/1/30/
    path('banned/<int:activity_id>/', views.banned, name='banned'), # /activity/banned/1/ 
]

AprendeAyudando/courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'
urlpatterns = [
    path('', views.index, name='index'), # /courses/
    path('inscription/<int:course_id>/', views.inscription, name='inscription'), # /courses/inscription/1/
    path('<int:course_id>/', views.join, name='join'), # /courses/curso/1
    path('leave/<int:course_id>/', views.leave, name='leave'), # /courses/leave/1/
    path('create/', views.createCourse, name='create'),
    path('update/<int:course_id>', views.update, name='update'),
    path('enrolled/', views.enrolled, name='enrolled'),
    path('delete/<int:course_id>/', views.delete, name='delete'), # /courses/delete/1/
    path('users/<int:course_id>/', views.users, name='users'), # /courses/users/1/
    path('removeUser/<int:course_id>/<int:user_id>/', views.removeUser, name='removeUser'),
    path('banned/<int:course_id>/', views.banned, name='banned'), # /courses/users/1/ 
]

AprendeAyudando/news/urls.py
from django.urls import path
from . import views
from news.views import (NewsList, NewsCreate, NewsDetail, NewsUpdate, NewsDelete)


app_name = 'news'
urlpatterns = [
    path('', NewsList.as_view(), name='news-list'),
    path('news/add/', NewsCreate.as_view(), name='news-add'),
    path('news/<int:pk>/update/', NewsUpdate.as_view(), name='news-update'),
    path('news/<int:pk>/delete/', NewsDelete.as_view(), name='news-delete'),
    path('news/<int:pk>/', NewsDetail.as_view(), name='news-detail'),
]

AprendeAyudando/quiz/urls.py
from django.urls import path
from . import views

app_name = 'quiz'
urlpatterns = [
    path('create/<str:courseOrActivity>/<int:courseOrActivity_id>/', views.createQuiz, name='createQuiz'),
    path('create/questions/<int:quiz_id>/<int:number_questions>/', views.createQuestions, name='createQuestions'),
    path('create/answers/<int:question_id>/<int:number_questions>/<int:number_answers>/', views.createAnswers, name='createAnswers'),
    path('startquiz/<int:quiz_id>/',views.startQuiz, name='startQuiz'),
    path('doquiz/<int:quiz_id>/', views.doQuiz, name='doQuiz'),
    path('doquiz/questionasked/<int:question_id>/', views.doQuizQuestionAsked, name='doQuizQuestionAsked'),
    path('deletequiz/<int:quiz_id>/', views.deleteQuiz, name='deleteQuiz'),
    path('administrationquiz/<int:quiz_id>/', views.administrationQuiz, name='administrationQuiz'),
    path('deletequestion/<int:question_id>/', views.deleteQuestion, name='deleteQuestion'),
    path('updatequestion/<int:question_id>/', views.updateQuestion, name='updateQuestion'),
    path('updateanswers/<int:question_id>/<int:number_answers>/', views.updateAnswers, name='updateAnswers'),
    path('updatequiz/<int:quiz_id>/', views.updateQuiz, name='updateQuiz'),
    path('viewqualifications/<int:quiz_id>/', views.viewQualifications, name='viewQualifications'),
]

AprendeAyudando/AprendeAyudando/views.py
from django.shortcuts import render
from django.contrib.auth.models import User, Group
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.contrib.auth import login, logout
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.core.mail import send_mail, EmailMultiAlternatives
from django.conf import settings
from .forms import RegisterForm, RecoverForm, UploadForm
import random
import string

def has_group(user, group_name):
    group = Group.objects.get(name=group_name)
    return True if group in user.groups.all() else False

def landingpage(request):
    grupo = 'Invitado'
    if request.user.has_perm('courses.view_course'):
        grupo = 'Estudiante'
    if request.user.has_perm('courses.add_course'):
        grupo = 'Profesor'
    if request.user.has_perm('activity.add_activity'):
        grupo = 'Entidad'

    context = {
        'grupo': grupo
    }
    return render(request, 'landingpage/index.html', context)

def news(request):
    return render(request, 'news/index.html')

@login_required
def account(request):
    return render(request, 'landingpage/account.html')

@login_required
def delete_account(request):
    if request.method == 'POST':
        if "cancel" in request.POST:
            return redirect('/account')
        else:
            request.user.delete()
            return redirect('/')

    return render(request, 'landingpage/delete_account.html')
    
def user_register(request):
    # if this is a POST request we need to process the form data
    template = 'registration/register.html'
   
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RegisterForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            if User.objects.filter(username=form.cleaned_data['username']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'El nombre de usuario ya existe.'
                })
            elif User.objects.filter(email=form.cleaned_data['email']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'El correo electrónico ya existe.'
                })
            elif form.cleaned_data['password'] != form.cleaned_data['password_repeat']:
                return render(request, template, {
                    'form': form,
                    'error_message': 'Las contraseñas no coinciden.'
                })
            else:
                # Create the user:
                user = User.objects.create_user(
                    form.cleaned_data['username'],
                    form.cleaned_data['email'],
                    form.cleaned_data['password']
                )
                user.first_name = form.cleaned_data['first_name']
                user.last_name = form.cleaned_data['last_name']
                user.save()
               
                # add role 'student' to new user
                studentGroup = Group.objects.get(name='Estudiante')
                studentGroup.user_set.add(user)

                # log the user in
                login(request, user)
               
                # redirect to accounts page
                return HttpResponseRedirect(reverse('account'))

   # No post data availabe, let's just show the page.
    else:
        form = RegisterForm()

    return render(request, template, {'form': form})

def recoverpassword(request):
    # if this is a POST request we need to process the form data
    template = 'registration/recoverpassword.html'
   
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        miForm = RecoverForm(request.POST)
        # check whether it's valid:
        if miForm.is_valid():
            if User.objects.filter(email=miForm.cleaned_data['email']).exists():
                # Minuto 19:19
                infForm=miForm.cleaned_data

                size = 12
                chars = string.ascii_uppercase+string.ascii_lowercase+string.digits

                newPass = ''.join(random.choice(chars) for x in range(size))
                
                user = User.objects.get(email=infForm['email'])
                user.set_password(newPass)
                user.save()

                subject = 'Solicitud de nueva contraseña'
                email_from = settings.EMAIL_HOST_USER 
                email_to = [infForm['email']]
                text_content = "ERROR"
                html_content = """  <table style="max-width: 600px; text-align: center; padding: 10px; margin:0 auto; border-collapse: collapse;">
                                        <tr>
                                            <td style="background-color: #ecf0f1; text-align: center; padding: 0">
                                                <a href="http://127.0.0.1:8000/">
                                                    <img width="20%" style="display:block; margin: 1.5% 3%; text-align: center;" src="https://aprendeayudando.herokuapp.com/static/general/images/logoTransparent.png">
                                                </a>
                                            </td>
                                        </tr>
                                        
                                        <tr>
                                            <td style="background-color: #ecf0f1">
                                                <div style="color: #34495e; margin: 4% 10% 2%; text-align: center;font-family: sans-serif">
                                                    <h2 style="color: #ff7d97; margin: 0 0 7px">¿Ha olvidado su contraseña?</h2>
                                                    <p style="margin: 2px; font-size: 15px">""" +  "Buenas, %s %s</p>" %(user.first_name, user.last_name) + """<p style="margin: 2px; font-size: 15px">
                                                        Ha solicitado una nueva contraseña en la plataforma AprendeAyudando, su nueva contraseña es: <strong>""" + "%s" %newPass + """</strong></p>
                                                    <br>
                                                    <div style="width: 100%; text-align: center">
                                                        <a style="text-decoration: none; border-radius: 5px; padding: 11px 23px; color: white; background-color: #3498db" href="http://127.0.0.1:8000/accounts/login/">Iniciar Sesión</a>	
                                                    </div>
                                                    <p style="color: #b3b3b3; font-size: 12px; text-align: center;margin: 30px 0 0">AprendeAyudando 2021</p>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>"""

                msg = EmailMultiAlternatives(subject, text_content, email_from, email_to)
                msg.attach_alternative(html_content, "text/html")
                msg.send()
                
                return render(request, template, {
                    'form': miForm,
                    'message': 'La nueva contraseña ha sido enviada a su correo electrónico.'
                })
            else:
                return render(request, template, {
                    'form': miForm,
                    'error_message': 'Inténtelo de nuevo. El correo electrónico no existe.'
                })
            

   # No post data availabe, let's just show the page.
    else:
        miForm = RecoverForm()

    return render(request, template, {'form': miForm})

@login_required
def modify(request, username):
    template = 'registration/modify.html'
    user = User.objects.get(username=username)
    if not request.user == user:
        return HttpResponseForbidden()
    modForm = UploadForm(instance=user)
    return render(request, template, {'form': modForm, 'username':username})

@login_required
def update(request, username):
    template = 'registration/modify.html'
    user = User.objects.get(username=username)
    userEmail = user.email
    modForm = UploadForm(request.POST, instance=user)
    if request.method == 'POST':
        if modForm.is_valid():

            infForm=modForm.cleaned_data
            email = infForm['email']
            password = infForm['password']
            confpassword = infForm['password_repeat']
            firstName = infForm['first_name']
            lastName = infForm['last_name']

            if User.objects.filter(email=email).exists() and userEmail != email:
                    return render(request, template, {
                        'form': modForm,
                        'error_message': 'El correo electrónico ya existe.'
                    })
            elif password != confpassword:
                    return render(request, template, {
                        'form': modForm,
                        'error_message': 'Las contraseñas no coinciden.'
                    })
            else:
                
                user.email = email
                user.first_name = firstName
                user.last_name = lastName
                
                if password != "":
                    user.set_password(password)
                    user.save()

                    subject = 'Cambio de contraseña'
                    email_from = settings.EMAIL_HOST_USER 
                    email_to = [infForm['email']]
                    text_content = "ERROR"
                    html_content = """  <table style="max-width: 600px; text-align: center; padding: 10px; margin:0 auto; border-collapse: collapse;">
                                            <tr>

AprendeAyudando/AprendeAyudando/templates/quiz/administrationquiz.html
{% extends "registration/base.html" %}
{% block title %}AprendeAyudando - Administración Test{% endblock %}
{% load auth_extras %}

{% block style %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'activity/style.css' %}">
{% endblock %}

{% block content %}
<section class="bg-white text-dark py-5 min-vh-100">
    <div class="container py-5">
        <div class="row">
            <div class="col-6">
                <h1>Editar Test</h1>
                <p>Título del test: <strong>{{ quiz.title }}</strong></p>
                <p>Descripción del test: <strong>{{ quiz.description }}</strong></p>
                {% if quiz.maximum_date is None %}
                    <p>Fecha límite: <strong>Sin fecha límite</strong></p>
                {% else %}
                    <p>Fecha límite: <strong>{{ quiz.maximum_date }}</strong></p>
                {% endif %}
                
                {% if quiz.repeatable %}
                    <p>El test es repetible: <strong class="text-success">SÍ</strong></p>
                {% else %}
                    <p>El test es repetible: <strong class="text-danger">NO</strong></p>
                {% endif %}

                {% if quiz.show_qualification %}
                    <p>Mostrar calificación: <strong class="text-success">SÍ</strong></p>
                {% else %}
                    <p>Mostrar calificación: <strong class="text-danger">NO</strong></p>
                {% endif %}

                {% if quiz.show_quiz %}
                    <p>Test público: <strong class="text-success">SÍ</strong></p>
                {% else %}
                    <p>Test público: <strong class="text-danger">NO</strong></p>
                {% endif %}
                <a href="{% url 'quiz:startQuiz' quiz.id %}" class="btn btn-sm btn-outline-dark">Volver al Test</a>
            </div>
            <div class="col-6 text-right">
                <a href="{% url 'quiz:updateQuiz' quiz.id %}" type="submit" class="btn btn-sm btn-warning">Editar campos</a>
                <a href="{% url 'quiz:deleteQuiz' quiz.id %}" class="btn btn-sm btn-danger">Borrar Test</a>
            </div>
            
        </div>
        
        <hr>
        <h2>Preguntas</h2>
        <p><strong>Cosas a tener en cuenta:</p>
        <p>- Si usted elimina una pregunta, todas las calificaciones de todos los alumnos serán calculadas de nuevo automáticamente.</p>
        <p>
            - Para editar una pregunta debe poner el test en privado. Si ya existe una calificación o una persona realizando el test,
            no podrá editar la pregunta, debe eliminar la pregunta y crear una nueva.
        </p></strong>
        <div class="row">
            <div class="col-12 text-right">
                <a href="{% url 'quiz:createQuestions' quiz.id 1 %}" class="btn btn-secondary" type="button">Añadir pregunta</a>
            </div>
        </div>
        <br>
        {% if list_questions %}
            <table class="table text-center">
                <thead>
                    <tr>
                        <th><strong style="font-size:20px">Preguntas</strong></th>
                        <th><strong style="font-size:20px">Posibles Respuestas</strong></th>
                        <th><strong style="font-size:20px">Acción</strong></th>
                    </tr>
                </thead>
                <tbody>
                {% for question in list_questions %}
                    <tr>
                        <td style="text-align: center; vertical-align: middle;"><strong>{{ question.text }}</strong></td>

                        <td style="text-align: left; vertical-align: middle;">
                            {% with list_answers=dic_answers|get_item_from_index:question.id %}
                                {% for answer in list_answers %}
                                    {% if answer.correct %}
                                        <p><strong class="text-success">&#10004; {{answer.text}}</strong></p>
                                    {% else %}
                                        <p><strong class="text-warning">&#10008; {{answer.text}}</strong></p>
                                    {% endif %}
                                {% endfor %}
                            {% endwith %}
                        </td>

                        <td style="vertical-align: middle;">
                            {% if quiz.show_quiz %}
                                <span class="d-inline-block" tabindex="0" data-bs-toggle="tooltip" title="Debe poner el test en Privado">
                                    <a href="#" type="submit" class="btn btn-warning disabled" aria-disabled="true">Editar</a>
                                </span>
                                <span class="d-inline-block" tabindex="0" data-bs-toggle="tooltip" title="Debe poner el test en Privado">
                                    <a href="#" class="btn btn-danger disabled" aria-disabled="true">Eliminar</a>
                                </span>
                            {% else %}
                                <a href="{% url 'quiz:updateQuestion' question.id %}" type="submit" class="btn btn-warning">Editar</a>
                                <a href="{% url 'quiz:deleteQuestion' question.id %}" class="btn btn-danger">Eliminar</a>
                            {% endif %}
                            
                        </td>

                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No hay preguntas disponibles.</p>
        {% endif %}
    </div>
</section>
{% endblock %}

AprendeAyudando/AprendeAyudando/templates/quiz/createanswers.html
{% extends "registration/base.html" %}
{% block title %}AprendeAyudando - Crear Test{% endblock %}

{% block style %} 
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'activity/style.css' %}">
{% endblock %}

{% block content %}
<section class="bg-white text-dark py-5 min-vh-100">
    <div class="container py-5 text-center">
        <h2>Crear Test - Posibles respuestas</h2>
        <p><strong>Posibles respuestas (selecciona también las respuestas correctas):</strong></p>
        <form action="{% url 'quiz:createAnswers' question.id number_questions number_answers %}" method="POST">
            {% csrf_token %}
            {% for nn in range_number_answers %}
                <div class="form-group row justify-content-center">
                    <label for="pregunta{{nn}}"></label>
                    <input class="form-control text-center col-4" type="text" name="new_answer_text{{nn}}" required>
                    <input class="form-control text-center col-1" type="checkbox" id="pregunta{{nn}}" name="new_answer_is_correct[]" value="{{nn}}">
                </div>
            {% endfor %}
            {% if number_questions > 1 %}
                <input type="submit" value="Siguiente pregunta" class="btn btn-success btn-lg"> 
            {% else %}
                <input type="submit" value="Terminar Test" class="btn btn-success btn-lg">
            {% endif %}
        </form>
    </div>
</section>
    
{% endblock %}

AprendeAyudando/AprendeAyudando/templates/quiz/createquestion.html
{% extends "registration/base.html" %}
{% block title %}AprendeAyudando - Crear Test{% endblock %}

{% block style %} 
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'activity/style.css' %}">
{% endblock %}

{% block content %}
<section class="bg-white text-dark py-5 min-vh-100">
    <div class="container py-5 text-center">
        {% if number_questions is 0 %}
            <h2>Creación del test finalizado. Ya ha realizado todas las preguntas.</h2>
            {% if is_course %}
                <a href="{% url 'courses:join' activity_or_course_id %}" class="btn btn-success btn-lg">Volver al curso</a>
            {% else %}
                <a href="{% url 'activity:join' activity_or_course_id %}" class="btn btn-success btn-lg">Volver a la actividad</a>
            {% endif %}
        {% else %}
            <h1>Crear Test - Preguntas</h1>
            
            <form action="{% url 'quiz:createQuestions' quiz.id number_questions %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="new_question_text"><strong>Escribe la pregunta:</strong></label>
                    <input type="text" name="new_question_text" class="form-control text-center"required>
                </div>
                <div class="form-group">
                    <label for="new_question_score"><strong>Puntuación por cada respuesta acertada:</strong></p></label>
                    <input class="form-control text-center col-1 mx-auto" type="number" min="0" name="new_question_score"required>
                </div>
                <div class="form-group">
                    <label for="new_question_negative_score"><strong>Puntuación negativa cada respuesta errónea:</strong></p></label>
                    <input class="form-control text-center col-1 mx-auto" type="number" max="0" name="new_question_negative_score"required>
                </div>
                <div class="form-group">
                    <label for="number_answers"><strong>Número de respuestas posibles:</strong></p></label>
                    <input class="form-control text-center col-1 mx-auto" type="number" name="number_answers" min="1" max="20" required>
                </div>
                <input type="submit" value="Realizar respuestas" class="btn btn-success btn-lg">
            </form>
        {% endif %}
    </div>
</section>
    
{% endblock %}

AprendeAyudando/AprendeAyudando/templates/quiz/startquiz.html
{% extends "registration/base.html" %}
{% block title %}AprendeAyudando - Realizar Test{% endblock %}

{% block style %} 
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'activity/style.css' %}">
{% endblock %}

{% block content %}
<section class="bg-white text-dark py-5 min-vh-100">
    <div class="container py-5">
        <!--Administracion-->
        {% if isOwner or user.is_superuser %}
            <h2>Administración</h2>
            <a href="{% url 'quiz:administrationQuiz' quiz.id %}" class="btn btn-warning">Editar Test</a>
            <a href="{% url 'quiz:viewQualifications' quiz.id %}" class="btn btn-danger">Ver calificaciones</a>
            <br>
        {% endif %}
        <!--Test-->
        <h2 style="margin-top: 60px;">Test</h2>
        {% if expired %}
            <p><strong>Este test ya no se puede realizar. Su fecha límite fue {{quiz.maximum_date}}</strong></p>
        {% else %}
            {% if not exist_started_qualification and not exist_finished_qualification %}
                <p>Esta seguro de inicializar el test <strong>{{quiz.title}}</strong>?</p>
                {% if quiz.course is not None %}
                    <a href="{% url 'courses:join' quiz.course.id %}" class="btn btn-outline-dark">Volver al curso</a>
                {% else %}
                    <a href="{% url 'activity:join' quiz.activity.id %}" class="btn btn-outline-dark">Volver a la actividad</a>
                {% endif %}
                <a href="{% url 'quiz:doQuiz' quiz.id %}" class="btn btn-secondary">Empezar Test</a>
            {% elif not exist_started_qualification and exist_finished_qualification and quiz.repeatable %}
                <p><strong>Ya ha realizado este test. Este Test se puede repetir. Desea repetir el Test?</strong></p>
                {% if quiz.course is not None %}
                    <a href="{% url 'courses:join' quiz.course.id %}" class="btn btn-outline-dark">Volver al curso</a>
                {% else %}
                    <a href="{% url 'activity:join' quiz.activity.id %}" class="btn btn-outline-dark">Volver a la actividad</a>
                {% endif %}
                <a href="{% url 'quiz:doQuiz' quiz.id %}" class="btn btn-secondary">Repetir Test</a>
            {% elif exist_started_qualification %}
                <p><strong>No ha terminado completamente el Test. Desea seguir con el Test?</strong></p>
                {% if quiz.course is not None %}
                    <a href="{% url 'courses:join' quiz.course.id %}" class="btn btn-outline-dark">Volver al curso</a>
                {% else %}
                    <a href="{% url 'activity:join' quiz.activity.id %}" class="btn btn-outline-dark">Volver a la actividad</a>
                {% endif %}
                <a href="{% url 'quiz:doQuiz' quiz.id %}" class="btn btn-secondary">Seguir con el Test</a>
            {% else %}
                <p>Ya ha terminado con el Test. Este test no se puede repetir.</p>
                {% if quiz.course is not None %}
                    <a href="{% url 'courses:join' quiz.course.id %}" class="btn btn-outline-dark">Volver al curso</a>
                {% else %}
                    <a href="{% url 'activity:join' quiz.activity.id %}" class="btn btn-outline-dark">Volver a la actividad</a>
                {% endif %}
            {% endif %}
        {% endif %}
    </div>
</section>
    
{% endblock %}

AprendeAyudando/AprendeAyudando/templates/quiz/viewqualifications.html
{% extends "registration/base.html" %}
{% block title %}AprendeAyudando - Ver Calificaciones{% endblock %}
{% load auth_extras %}

{% block style %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'activity/style.css' %}">
{% endblock %}

{% block content %}
    <section class="bg-white text-dark py-5 min-vh-100">
        <div class="container py-5 text-center">
            <h1>Calificaciones</h1>
            {% if list_qualification %}
                <table class="table text-center">
                    <thead>
                        <tr>
                            <th width="33%"><strong style="font-size:20px">Usuario</strong></th>
                            <th width="33%"><strong style="font-size:20px">Nombre y Apellido</strong></th>
                            <th width="33%"><strong style="font-size:20px">Máxima Calificacion</strong></th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for qualification in list_qualification %}
                        {% with this_user=querySet_of_users|get_user_from_id:qualification.user %}
                            <tr>
                                <td style="vertical-align: middle;"><strong>{{ this_user.username }}</strong></td>
                                <td style="vertical-align: middle;"><strong>{{ this_user.first_name }} {{ this_user.last_name }}</strong></td>
                                <td style="vertical-align: middle;"><strong>{{ qualification.max_score }} / {{ max_qualification }}</strong></td>
                            </tr>
                        {% endwith %}
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No existen calificaciones disponibles.</p>
            {% endif %}
            {% if is_course %}
                <a href="{% url 'courses:join' quiz.course.id %}" class="btn btn-outline-dark">Volver al curso</a>
            {% else %}
                <a href="{% url 'activity:join' quiz.activity.id %}" class="btn btn-outline-dark">Volver a la actividad</a>
            {% endif %}
        </div>

    </section>
{% endblock %}